const mongoose = require("mongoose");

const employeeSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB (don’t define manually) :contentReference[oaicite:11]{index=11}
        first_name: { type: String, required: true, trim: true }, // :contentReference[oaicite:12]{index=12}
        last_name: { type: String, required: true, trim: true },  // :contentReference[oaicite:13]{index=13}
        email: { type: String, unique: true, sparse: true, trim: true, lowercase: true }, // :contentReference[oaicite:14]{index=14}
        gender: {
        type: String,
        enum: ["Male", "Female", "Other"], // :contentReference[oaicite:15]{index=15}
        },
        designation: { type: String, required: true, trim: true }, // :contentReference[oaicite:16]{index=16}
        salary: {
        type: Number,
        required: true,
        min: 1000, // must be >= 1000 :contentReference[oaicite:17]{index=17}
        },
        date_of_joining: { type: Date, required: true }, // :contentReference[oaicite:18]{index=18}
        department: { type: String, required: true, trim: true }, // :contentReference[oaicite:19]{index=19}
        employee_photo: { type: String }, // store image path/url (Cloudinary) :contentReference[oaicite:20]{index=20}
    },
    {
        timestamps: { createdAt: "created_at", updatedAt: "updated_at" }, // :contentReference[oaicite:21]{index=21}
    }
);

module.exports = mongoose.model("Employee", employeeSchema);
