const mongoose = require("mongoose");

const userSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB (don’t define manually) :contentReference[oaicite:6]{index=6}
        username: {
        type: String,
        required: true,
        unique: true, // “Primary Key” concept in assignment :contentReference[oaicite:7]{index=7}
        trim: true,
        minlength: 1,
        },
        email: {
        type: String,
        required: true,
        unique: true, // :contentReference[oaicite:8]{index=8}
        trim: true,
        lowercase: true,
        },
        password: {
        type: String,
        required: true, // encrypted value stored :contentReference[oaicite:9]{index=9}
        },
    },
    {
        timestamps: { createdAt: "created_at", updatedAt: "updated_at" }, // :contentReference[oaicite:10]{index=10}
    }
);

module.exports = mongoose.model("User", userSchema);
